# Generated by Django 3.2.4 on 2021-07-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetables', '0004_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.ImageField(default='', upload_to='uploads/products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(default='', upload_to='uploads/products/'),
        ),
    ]
