# Generated by Django 3.2.4 on 2021-07-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetables', '0005_auto_20210705_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='benefits',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='benefits1',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='benefits2',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='description1',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='description2',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
